# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Published'), (2, 'Draft'), (3, 'Archived')], default=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to='covers'),
        ),
    ]
