# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170712_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Hidden'), (2, 'Visible'), (3, 'Deleted')], default=1),
        ),
    ]
